from dataclasses import dataclass


@dataclass
class ThemeColors:
    title_color: str
    text_color: str
    icon_color: str
    bg_color: str
    border_color: str


THEMES: dict[str, ThemeColors] = {
    "default": ThemeColors(
        title_color="2f80ed",
        text_color="434d58",
        icon_color="4c71f2",
        bg_color="fffefe",
        border_color="e4e2e2",
    ),
    "dark": ThemeColors(
        title_color="fff",
        text_color="9f9f9f",
        icon_color="79ff97",
        bg_color="151515",
        border_color="e4e2e2",
    ),
    "radical": ThemeColors(
        title_color="fe428e",
        text_color="a9fef7",
        icon_color="f8d847",
        bg_color="141321",
        border_color="141321",
    ),
    "merko": ThemeColors(
        title_color="abd200",
        text_color="68b587",
        icon_color="b7d364",
        bg_color="0a0f0b",
        border_color="0a0f0b",
    ),
    "gruvbox": ThemeColors(
        title_color="fabd2f",
        text_color="ebdbb2",
        icon_color="fe8019",
        bg_color="282828",
        border_color="282828",
    ),
    "gruvbox_light": ThemeColors(
        title_color="b57614",
        text_color="3c3836",
        icon_color="af3a03",
        bg_color="fbf1c7",
        border_color="fbf1c7",
    ),
    "tokyonight": ThemeColors(
        title_color="70a5fd",
        text_color="38bdae",
        icon_color="bf91f3",
        bg_color="1a1b27",
        border_color="1a1b27",
    ),
    "onedark": ThemeColors(
        title_color="e4bf7a",
        text_color="df6d74",
        icon_color="8eb573",
        bg_color="282c34",
        border_color="282c34",
    ),
    "cobalt": ThemeColors(
        title_color="e683d9",
        text_color="75eeb2",
        icon_color="0480ef",
        bg_color="193549",
        border_color="193549",
    ),
    "synthwave": ThemeColors(
        title_color="e2e9ec",
        text_color="e5289e",
        icon_color="ef8539",
        bg_color="2b213a",
        border_color="2b213a",
    ),
    "highcontrast": ThemeColors(
        title_color="e7f216",
        text_color="fff",
        icon_color="00ffff",
        bg_color="000",
        border_color="e4e2e2",
    ),
    "dracula": ThemeColors(
        title_color="ff6e96",
        text_color="f8f8f2",
        icon_color="bd93f9",
        bg_color="282a36",
        border_color="282a36",
    ),
    "prussian": ThemeColors(
        title_color="bddfff",
        text_color="6e93b5",
        icon_color="38a0ff",
        bg_color="172f45",
        border_color="172f45",
    ),
    "monokai": ThemeColors(
        title_color="eb1f6a",
        text_color="f1f1eb",
        icon_color="e28905",
        bg_color="272822",
        border_color="272822",
    ),
    "vue": ThemeColors(
        title_color="41b883",
        text_color="273849",
        icon_color="41b883",
        bg_color="fffefe",
        border_color="e4e2e2",
    ),
    "vue_dark": ThemeColors(
        title_color="41b883",
        text_color="fffefe",
        icon_color="41b883",
        bg_color="273849",
        border_color="273849",
    ),
    "shades_of_purple": ThemeColors(
        title_color="fad000",
        text_color="a599e9",
        icon_color="b362ff",
        bg_color="2d2b55",
        border_color="2d2b55",
    ),
    "nightowl": ThemeColors(
        title_color="c792ea",
        text_color="7fdbca",
        icon_color="ffeb95",
        bg_color="011627",
        border_color="011627",
    ),
    "buefy": ThemeColors(
        title_color="7957d5",
        text_color="363636",
        icon_color="7957d5",
        bg_color="ffffff",
        border_color="e4e2e2",
    ),
    "algolia": ThemeColors(
        title_color="00aeff",
        text_color="ffffff",
        icon_color="2dde98",
        bg_color="050f2c",
        border_color="050f2c",
    ),
    "great_gatsby": ThemeColors(
        title_color="ffa726",
        text_color="ffd95b",
        icon_color="ffb74d",
        bg_color="000000",
        border_color="000000",
    ),
    "darcula": ThemeColors(
        title_color="ba5f17",
        text_color="bebebe",
        icon_color="84628b",
        bg_color="242424",
        border_color="242424",
    ),
    "bear": ThemeColors(
        title_color="e03c8a",
        text_color="bcb28d",
        icon_color="00aabb",
        bg_color="1f2023",
        border_color="1f2023",
    ),
    "solarized_dark": ThemeColors(
        title_color="268bd2",
        text_color="839496",
        icon_color="b58900",
        bg_color="002b36",
        border_color="002b36",
    ),
    "solarized_light": ThemeColors(
        title_color="268bd2",
        text_color="586e75",
        icon_color="b58900",
        bg_color="fdf6e3",
        border_color="fdf6e3",
    ),
    "chartreuse_dark": ThemeColors(
        title_color="7fff00",
        text_color="fff",
        icon_color="00aeff",
        bg_color="000",
        border_color="000",
    ),
    "nord": ThemeColors(
        title_color="81a1c1",
        text_color="d8dee9",
        icon_color="88c0d0",
        bg_color="2e3440",
        border_color="2e3440",
    ),
    "apex": ThemeColors(
        title_color="7EB77F",
        text_color="ABABAB",
        icon_color="F47067",
        bg_color="141414",
        border_color="141414",
    ),
    "material_palenight": ThemeColors(
        title_color="c792ea",
        text_color="a6accd",
        icon_color="89ddff",
        bg_color="292d3e",
        border_color="292d3e",
    ),
    "graywhite": ThemeColors(
        title_color="24292e",
        text_color="24292e",
        icon_color="24292e",
        bg_color="ffffff",
        border_color="e4e2e2",
    ),
    "vision_friendly_dark": ThemeColors(
        title_color="ffb000",
        text_color="ffffff",
        icon_color="785ef0",
        bg_color="000000",
        border_color="000000",
    ),
    "ayu_mirage": ThemeColors(
        title_color="f4cd7c",
        text_color="c7c8c2",
        icon_color="73d0ff",
        bg_color="1f2430",
        border_color="1f2430",
    ),
    "midnight_purple": ThemeColors(
        title_color="9745f5",
        text_color="ffffff",
        icon_color="9f4bff",
        bg_color="000000",
        border_color="000000",
    ),
    "calm": ThemeColors(
        title_color="e07f5f",
        text_color="ebcfb2",
        icon_color="e07f5f",
        bg_color="373f51",
        border_color="373f51",
    ),
    "flag_india": ThemeColors(
        title_color="ff8f1c",
        text_color="509b4b",
        icon_color="250e6",
        bg_color="ffffff",
        border_color="e4e2e2",
    ),
    "omni": ThemeColors(
        title_color="ff79c6",
        text_color="e1e1e6",
        icon_color="e7de79",
        bg_color="191622",
        border_color="191622",
    ),
    "react": ThemeColors(
        title_color="61dafb",
        text_color="ffffff",
        icon_color="61dafb",
        bg_color="20232a",
        border_color="20232a",
    ),
    "jolly": ThemeColors(
        title_color="ff64da",
        text_color="a695c7",
        icon_color="a695c7",
        bg_color="291b3e",
        border_color="291b3e",
    ),
    "noctis_minimus": ThemeColors(
        title_color="d3b692",
        text_color="c5cdd3",
        icon_color="72b7c0",
        bg_color="1b2932",
        border_color="1b2932",
    ),
    "kacho_ga": ThemeColors(
        title_color="bf4a3f",
        text_color="d9c8a9",
        icon_color="a64833",
        bg_color="402b23",
        border_color="402b23",
    ),
    "outrun": ThemeColors(
        title_color="ffcc00",
        text_color="8080ff",
        icon_color="ff1aff",
        bg_color="141439",
        border_color="141439",
    ),
    "ocean_dark": ThemeColors(
        title_color="8957B2",
        text_color="92D534",
        icon_color="FFFFFF",
        bg_color="151A28",
        border_color="151A28",
    ),
    "github_dark": ThemeColors(
        title_color="58a6ff",
        text_color="c9d1d9",
        icon_color="1f6feb",
        bg_color="0d1117",
        border_color="30363d",
    ),
    "github_dark_dimmed": ThemeColors(
        title_color="539bf5",
        text_color="adbac7",
        icon_color="539bf5",
        bg_color="22272e",
        border_color="444c56",
    ),
    "transparent": ThemeColors(
        title_color="006AFF",
        text_color="417E87",
        icon_color="0579C3",
        bg_color="00000000",
        border_color="e4e2e2",
    ),
    "catppuccin_latte": ThemeColors(
        title_color="1e66f5",
        text_color="4c4f69",
        icon_color="fe640b",
        bg_color="eff1f5",
        border_color="bcc0cc",
    ),
    "catppuccin_mocha": ThemeColors(
        title_color="89b4fa",
        text_color="cdd6f4",
        icon_color="fab387",
        bg_color="1e1e2e",
        border_color="313244",
    ),
    "rose_pine": ThemeColors(
        title_color="9ccfd8",
        text_color="e0def4",
        icon_color="c4a7e7",
        bg_color="191724",
        border_color="191724",
    ),
    "one_dark_pro": ThemeColors(
        title_color="61afef",
        text_color="abb2bf",
        icon_color="e4bf7a",
        bg_color="282c34",
        border_color="282c34",
    ),
    "holi": ThemeColors(
        title_color="5BCDEC",
        text_color="E0E7EC",
        icon_color="1E9BEA",
        bg_color="0D1117",
        border_color="0D1117",
    ),
    "neon": ThemeColors(
        title_color="00FFF0",
        text_color="FFFFFF",
        icon_color="FF00FF",
        bg_color="000000",
        border_color="FF00FF",
    ),
    "blue_green": ThemeColors(
        title_color="0AECDB",
        text_color="99FEFF",
        icon_color="0AECDB",
        bg_color="091c29",
        border_color="091c29",
    ),
}


def resolve_colors(
    theme: str | None = None,
    title_color: str | None = None,
    text_color: str | None = None,
    icon_color: str | None = None,
    bg_color: str | None = None,
    border_color: str | None = None,
) -> ThemeColors:
    """Resolve final colors: start with theme, override with explicit params."""
    base = THEMES.get(theme or "default", THEMES["default"])
    return ThemeColors(
        title_color=title_color or base.title_color,
        text_color=text_color or base.text_color,
        icon_color=icon_color or base.icon_color,
        bg_color=bg_color or base.bg_color,
        border_color=border_color or base.border_color,
    )
